topics:
  - topic: "postgres.public.customers"
    table: "customers"
    bronze_path: ""
    checkpoint_bronze: ""
    
  - topic: "postgres.public.orders"
    table: "orders"
    bronze_path: ""
    checkpoint_bronze: ""
    
  - topic: "postgres.public.products"
    table: "products"
    bronze_path: ""
    checkpoint_bronze: ""

tables:
  - name: "customers"
    bronze_path: ""
    silver_path: ""
    checkpoint_silver: ""
    schema_name: "customers"

  - name: "orders"
    bronze_path: ""
    silver_path: ""
    checkpoint_silver: ""
    schema_name: "orders"

  - name: "products"
    bronze_path: ""
    silver_path: ""
    checkpoint_silver: ""
    schema_name: "products"

gold:
  base_path: ""